[phases.setup]
<<<<<<< HEAD
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci"]
=======
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install"]
>>>>>>> 977022b4e2c96e2f5dbd2736064f2ea6e482d209

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
